-- MySQL Script generated by MySQL Workbench
-- Fri Feb 13 10:18:38 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Gkt
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Gkt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Gkt` DEFAULT CHARACTER SET utf8 ;
USE `Gkt` ;

-- -----------------------------------------------------
-- Table `Gkt`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gkt`.`users` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `email_user` VARCHAR(100) NOT NULL,
  `password_user` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `email_user_UNIQUE` (`email_user` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gkt`.`plans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gkt`.`plans` (
  `id_plan` INT NOT NULL AUTO_INCREMENT,
  `type_plan` INT NOT NULL,
  `monthlyprice_plan` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_plan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gkt`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gkt`.`students` (
  `id_student` INT NOT NULL AUTO_INCREMENT,
  `name_student` VARCHAR(45) NOT NULL,
  `cpf_student` VARCHAR(11) NOT NULL,
  `bornday_student` DATE NOT NULL,
  `genre_student` VARCHAR(5) NOT NULL,
  `phone_student` VARCHAR(20) NOT NULL,
  `signupdate_student` DATE NOT NULL,
  `plans_id_plan` INT NOT NULL,
  PRIMARY KEY (`id_student`, `plans_id_plan`),
  UNIQUE INDEX `cpf_student_UNIQUE` (`cpf_student` ASC) ,
  INDEX `fk_students_plans1_idx` (`plans_id_plan` ASC) ,
  CONSTRAINT `fk_students_plans1`
    FOREIGN KEY (`plans_id_plan`)
    REFERENCES `Gkt`.`plans` (`id_plan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gkt`.`teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gkt`.`teachers` (
  `id_teacher` INT NOT NULL AUTO_INCREMENT,
  `name_teacher` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id_teacher`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gkt`.`sports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gkt`.`sports` (
  `id_sport` INT NOT NULL AUTO_INCREMENT,
  `type_sport` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_sport`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gkt`.`situation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gkt`.`situation` (
  `id_situation` INT NOT NULL AUTO_INCREMENT,
  `status_situation` TINYINT NOT NULL,
  `students_id_student` INT NOT NULL,
  PRIMARY KEY (`id_situation`, `students_id_student`),
  INDEX `fk_situation_students1_idx` (`students_id_student` ASC) ,
  CONSTRAINT `fk_situation_students1`
    FOREIGN KEY (`students_id_student`)
    REFERENCES `Gkt`.`students` (`id_student`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gkt`.`students_has_sports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gkt`.`students_has_sports` (
  `students_id_student` INT NOT NULL,
  `sports_id_sport` INT NOT NULL,
  PRIMARY KEY (`students_id_student`, `sports_id_sport`),
  INDEX `fk_students_has_sports_sports1_idx` (`sports_id_sport` ASC) ,
  INDEX `fk_students_has_sports_students_idx` (`students_id_student` ASC) ,
  CONSTRAINT `fk_students_has_sports_students`
    FOREIGN KEY (`students_id_student`)
    REFERENCES `Gkt`.`students` (`id_student`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_students_has_sports_sports1`
    FOREIGN KEY (`sports_id_sport`)
    REFERENCES `Gkt`.`sports` (`id_sport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gkt`.`sports_has_teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gkt`.`sports_has_teachers` (
  `sports_id_sport` INT NOT NULL,
  `teachers_id_teacher` INT NOT NULL,
  PRIMARY KEY (`sports_id_sport`, `teachers_id_teacher`),
  INDEX `fk_sports_has_teachers_teachers1_idx` (`teachers_id_teacher` ASC) ,
  INDEX `fk_sports_has_teachers_sports1_idx` (`sports_id_sport` ASC) ,
  CONSTRAINT `fk_sports_has_teachers_sports1`
    FOREIGN KEY (`sports_id_sport`)
    REFERENCES `Gkt`.`sports` (`id_sport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sports_has_teachers_teachers1`
    FOREIGN KEY (`teachers_id_teacher`)
    REFERENCES `Gkt`.`teachers` (`id_teacher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
